name: Robot Framework Tests

# Aciona o workflow em eventos de push ou pull request
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest  # Define o ambiente de execução como Ubuntu

    steps:
      # Passo 1: Checa o código no repositório
      - name: Checkout repository
        uses: actions/checkout@v3

      # Passo 2: Configura o Python no ambiente
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.2'  # Escolha a versão do Python que seu projeto usa

      # Passo 3: Instala dependências
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install robotframework

            # Passo 4: Executa os testes do Robot Framework
      - name: Run Robot Framework tests
        run: |
          robot --outputdir results/ tests/test.robot