name: Robot Framework Tests

on: [push]

jobs:
  robot-test:
    runs-on: ubuntu-22.04
    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install robotframework
          pip install robotframework-seleniumlibrary
          pip install selenium

      # Run Robot Framework tests
      - name: Run Robot Framework Tests
        run: |
          robot tests/test.robot

      # Store test results as artifacts
      - name: Archive Robot Framework Results
        uses: actions/upload-artifact@v3
        with:
          name: robot-results
          path: output/*
